# fly.toml
app = "santuario-nazare-cohatrac"  # <-- troque para o nome do seu app no Fly

primary_region = "gru"  # ou ewr/mia etc, escolha a mais próxima de você

[build]
  # usando Dockerfile da raiz (nada a declarar aqui)

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

[deploy]
  # roda migrations a cada deploy
  release_command = "python manage.py migrate --noinput"
