app = "santuario-nazare-cohatrac"
primary_region = "gru"

[build]
  # com Dockerfile no repo, o Fly usa ele automaticamente

[env]
  DJANGO_SETTINGS_MODULE = "core.settings"
  PYTHONUNBUFFERED = "1"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]
