name: Deploy to Fly.io

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy no Fly.io
        run: flyctl deploy --remote-only --app santuario-nazare-cohatrac
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
