# .github/workflows/deploy.yml
name: Deploy to Fly.io

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar o Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy para Fly.io
        run: flyctl deploy --remote-only --app ${{ secrets.FLY_APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
